config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :friends
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
  has_many :posts

  ##...Avatar Attachment...##
  has_one_attached :avatar 
  validates :birthdate, :presence => true
  validate :validate_age

  private
  def validate_age
    if birthdate.present? && birthdate > 13.years.ago.to_date
        errors.add(:birthdate, 'You should be over 13 years old.')
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :gender, :birthdate)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :first_name, :last_name, :email, :password, :current_password, :gender, :birthdate)}
        end
end 

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
    #Empty method
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
    #Empty method
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #Empty function
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    #Empty function
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    #Empty function
  end

  # POST /posts or /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not Authorized to edit this post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div class="mb-3 form-group">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <td><%= friend.name %></td>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td><%= link_to "Show" , friend, class:"btn btn-primary" %></td>
  <td><%= link_to "Edit" , edit_friend_path(friend), class:"btn btn-secondary" %></td>
  <td><%= link_to "Destroy", friend, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<div class="container content">
  <div class="row justify-content-center">
    <div class="table_config" class="col-lg-6">
      <p style="color: green">
        <%= notice %>
      </p>
      <h1>Friends</h1>
      <table class="table table-light table-hover">
        <caption>Lista de amigos</caption>
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
            <th scope="col">Telefone</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <% if friend.user==current_user %>
              <tr>
                <%= render friend %>
              </tr>
              <% end %>
                <% end %>
        </tbody>
      </table>  
      <%= link_to "New friend" , new_friend_path, class: "btn btn-primary mb-5" %>
    </div>
  </div>
</div>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/_footer.html.erb
<footer class="footer_config"></footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'VSConnect', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav  mb-2 mb-lg-0">
        </li>
        <% if !user_signed_in?%>
            <li class="nav-item mb-2">
                <%= link_to 'Cadastre-se', new_user_registration_path, class:"btn btn-primary", id:"teste"%>
            </li>
            <li class="nav-item mb-2">
                <%= link_to 'Login', new_user_session_path, class:"btn btn-secondary"%>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Amigos', friends_path, class:"nav-link"%>
            <li class="nav-item">
            <li class="nav-item">
                <%= link_to 'Posts', posts_path, class:"nav-link"%>
            <li class="nav-item">
                <%= link_to 'Meu Perfil', edit_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sair', destroy_user_session_path, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"nav-link"%>
            </li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container content">
    <div class="row my-5">
        <div class="col-lg-6 my-3">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center">Lorem Ipsum</h1>
                    <hr>
                    <p>Lorem ipsum dolor sit amet. In aperiam eius sit minus voluptatem qui laboriosam
                        rerum
                        id
                        iure Quis ex neque nemo sed odit modi! Ut molestiae delectus qui provident magnam qui dolor
                        omnis
                        sit
                        iure nihil et iste alias in ratione cumque aut officiis recusandae. Sed quisquam provident eos
                        accusantium exercitationem id deserunt quos ut iure galisum et amet galisum.</p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 my-3">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center">Lorem Ipsum</h1>
                    <hr>
                    <p class="p-text">Lorem ipsum dolor sit amet. In aperiam eius sit minus voluptatem qui laboriosam
                        rerum
                        id
                        iure Quis ex neque nemo sed odit modi! Ut molestiae delectus qui provident magnam qui dolor
                        omnis
                        sit
                        iure nihil et iste alias in ratione cumque aut officiis recusandae. Sed quisquam provident eos
                        accusantium exercitationem id deserunt quos ut iure galisum et amet galisum.</p>
                </div>
            </div>
        </div>
    </div>

</div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VSconnect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "app", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
   <%= render 'home/header' %>
   <%= yield %>
    <%= render 'home/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div class="mb-3 form-group">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
 <td><%= post.title %></td>
  <td><%= post.content %></td>
  <td><%= link_to "Show" , post, class:"btn btn-primary" %></td>
  <td><%= link_to "Edit" , edit_friend_path(post), class:"btn btn-secondary" %></td>
  <td><%= link_to "Destroy", post, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
 </div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container content">
  <div class="row justify-content-center">
    <div class="table_config" class="col-lg-6">
      <p style="color: green">
        <%= notice %>
      </p>
      <h1>Posts</h1>
      <table class="table table-light table-hover">
        <caption>Posts</caption>
        <thead>
          <tr>
            <th scope="col">Título</th>
            <th scope="col">Conteúdo</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <% if post.user==current_user %>
            <%= render post %>
              <% end %>
                <% end %>
        </tbody>
      </table>  
      <%= link_to "New post" , new_post_path, class: "btn btn-primary mb-5" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>